### ISSUE TITLE
Manually Bootstrap Angular Application

### ISSUE THREAD

**Issue by alexsomeoddpilot** [alexsomeoddpilot/someoddpilot#3]
> Angular initializes automatically upon DOMContentLoaded event or when the angular.js script is evaluated if at that time document.readyState is set to 'complete'.

Because you’re using the async script loading method, you’ll need to [manually bootstrap your application.](https://docs.angularjs.org/guide/bootstrap) I’ve had some luck automatically initializing with async scripts, but the manual method is foolproof.

This will solve issues relating to the module.

**Comment by krispy1298** [comment]
can you check 77dc0da and see what im doing wrong?

**Comment by alexsomeoddpilot** [comment]
Remove the `ng-app` attribute from the body.

```patch
  <link rel="stylesheet" type="text/css" href="/css/style.css">
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript" charset="utf-8"></script>
 </head>
-<body class="{{ template }} {{#compare template "contains" "news"}}yellow-bg{{else}}{{#if color}}{{color}}{{else}}yellow{{/if}}-bg{{/compare}}"
-  ng-app="sop">
+<body class="{{ template }} {{#compare template "contains" "news"}}yellow-bg{{else}}{{#if color}}{{color}}{{else}}yellow{{/if}}-bg{{/compare}}">

   <header class="full top-header{{#compare template "contains" "work-detail"}} header-no-push{{/compare}}"  ng-controller="headerController" ng-class="{active:header.active}">
     <a href="#" class="nav-icon" ng-click="toggleActive(header)">
```
