### ISSUE TITLE
Gulp `about` task should be split into two tasks

### ISSUE THREAD

**Issue by alexsomeoddpilot** [alexsomeoddpilot/someoddpilot#5]
Currently the about task has two `gulp.src` calls, the first of which is being returned. Multiple `gulp.src` calls are valid, but not really necessary. Create subtasks for each call.

**Comment by krispy1298** [comment]
https://github.com/krispy1298/someoddpilot/commit/eeee55f297e75bfec839f5ebe16bafad4fc47cf1

**Comment by alexsomeoddpilot** [comment]
That works.
