### ISSUE TITLE
`timer` is uninitialized in `slider/index.js`

### ISSUE THREAD

**Issue by alexsomeoddpilot** [alexsomeoddpilot/someoddpilot#6]
[the `timer` variable is uninitialized](https://github.com/krispy1298/someoddpilot/blob/master/slider/index.js#L36). Initialize it with a `var` statement.

**Comment by krispy1298** [comment]
https://github.com/krispy1298/someoddpilot/commit/5407b5abb5f8460687a5f5c0c1cf11f64810af00#diff-462146c055a373a9566b06d2577679b5R69
